substitutions:
  name: hello
  board: 'esp32-s3-devkitc-1'
  friendly_name: 'hello'
  device_name: 'hello'
  node_name: 'nesp'
  device_description: 'Rotary Display thermostat on ZX2D10GE01R-V4848 with WT32-S3-WROVER-N16R8 with ST7701S display'  
  project_base: 'Veli'
  project_name: 'Knob'
  project_version: '0.2'

  static_ip: 192.168.0.124

  ## HA Entities
  climate_entity: climate.ac_living_room
  min_value: "15"
  max_value: "35"
  initial_value: "21"
  light_entity_lounge: light.lounge_dimmer_2

 
  # for QR code generating
  ap_ssid: ${device_name}
  ap_password: ${device_name}
  ap_guest_ssid: !secret ap_guest_ssid
  ap_guest_password: !secret ap_guest_password

<<: !include common.yaml

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  comment: ${device_description}
  on_boot:
    - light.turn_on:
        id: led_ring
        effect: rainbow

  platformio_options:
    board_build.flash_mode: dio
    board_build.arduino.memory_type: qio_opi

external_components:
  - source: github://pr#4330
    components: [internal_temperature]
    refresh: always
  ## Shouldn't need any longer ##
  # - source: github://clydebarrow/esphome@lvgl_original
  #   refresh: 10min
  #   components: [ lvgl ]

esp32:
  board: ${board}
  variant: esp32s3
  flash_size: 16MB
  framework:
    type: esp-idf
    version: recommended
    ##JUST ADDED##
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

web_server:

esp32_ble_tracker:

bluetooth_proxy:
  active: true

globals:
  - id: cpu_speed
    type: int
    restore_value: no
    initial_value: '0'

improv_serial:

packages:
  colors: !include nesp/colors/homeassistant


debug:
  update_interval: 30s


sensor:

  - platform: rotary_encoder
    name: "${friendly_name} Rotary Encoder"
    id: rotaryencoder
    pin_a: 
      number: GPIO6
      mode: INPUT
      #  input: true
      #  pullup: true
    pin_b: 
      number: GPIO5
      mode: INPUT
      #  input: true
      #  pullup: true
    min_value: 0
    max_value: 25
    publish_initial_value: true
    # filters:
    #   debounce: 30ms
    restore_mode: ALWAYS_ZERO
    filters:
      - or:
        - debounce: 0.1s
        - delta: 10
    on_value:
      then:
        - homeassistant.service:
            service: light.turn_on
            data_template:
              entity_id: light.lounge_dimmer_2
              brightness_pct: "{{ brightness_1 | int }}"
            variables:
              brightness_1: 'return id(rotaryencoder).state * 4;'


  - platform: internal_temperature
    name: "Internal Temperature"

  - platform: uptime
    id: sys_uptime
    name: Uptime Sensor
    update_interval: 60s

  - platform: wifi_signal
    name: RSSI
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: template
    id: esp_memory
    icon: mdi:memory
    name: ESP Free Memory
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL) / 1024;
    unit_of_measurement: 'kB'
    state_class: measurement
    entity_category: "diagnostic"
    update_interval: 60s

  - platform: homeassistant
    entity_id: $climate_entity
    id: current_temperature
    entity_category: "diagnostic"
    internal: false
    attribute: current_temperature
    on_value:
      - script.execute: display_on

  - platform: homeassistant
    entity_id: ${climate_entity}
    entity_category: "diagnostic"
    id: min_temp
    internal: false
    attribute: min_temp

  - platform: homeassistant
    entity_id: $climate_entity
    entity_category: "diagnostic"
    id: max_temp
    internal: false
    attribute: max_temp

  - platform: homeassistant
    entity_id: ${climate_entity}
    id: target_temperature
    entity_category: "diagnostic"
    attribute: temperature
    internal: false

  - platform: homeassistant
    entity_id: ${climate_entity}
    id: target_temp_high
    entity_category: "diagnostic"
    attribute: target_temp_high
    internal: false

  - platform: homeassistant
    entity_id: ${climate_entity}
    id: target_temp_low
    entity_category: "diagnostic"
    attribute: target_temp_low
    internal: false

text_sensor:

  - platform: homeassistant
    entity_id: ${climate_entity}
    id: hvac_mode
    entity_category: "diagnostic"
    internal: false

  - platform: homeassistant
    entity_id: ${climate_entity}
    id: hvac_action
    entity_category: "diagnostic"
    internal: false
    attribute: hvac_action

  - platform: homeassistant
    entity_id: ${climate_entity}
    id: preset_mode
    entity_category: "diagnostic"
    internal: false
    attribute: preset_mode

time:
  - platform: sntp
    id: time_now

button:
  # - platform: restart
  #   icon: mdi:power-cycle
  #   name: "${device_name} Reboot"

  # - platform: factory_reset
  #   disabled_by_default: True
  #   name: "${device_name} Factory Reset"
  #   id: factory_reset_al
  
  - platform: template      # Home assistant control
    id: ${device_name}_light_decrease
    name: "${device_name} Light Decrease"
    icon: "mdi:vibrate"
    on_press:  
      - homeassistant.service:
          service: script.lounge_dimmer_decrease  
  - platform: template      # Home assistant control
    id: ${device_name}_light_increase
    name: "${device_name} Light Increase"
    icon: "mdi:vibrate"
    on_press:  
      - homeassistant.service:
          service: script.lounge_dimmer_increase

output:
  ### BACKLIGHT
  - platform: ledc
    id: ${device_name}_led_backlight
    pin: GPIO38
    zero_means_zero: true

light:
  - platform: monochromatic
    id: ${device_name}_backlight
    output: ${device_name}_led_backlight
    icon: mdi:brightness-percent
    name: Backlight
    internal: false
    default_transition_length: 500ms
    restore_mode: ALWAYS_ON

  - platform: esp32_rmt_led_strip
    id: led_ring
    name: "${friendly_name} RGB LED Ring"
    pin: GPIO4
    num_leds: 13
    rmt_channel: 0
    rgb_order: GRB
    chipset: ws2812
    restore_mode: ALWAYS_ON
    effects:
      - pulse:
      - random:
      - strobe:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:

switch: 
  - platform: gpio
    pin: 
      number: 7 #Vibrating motor |	Feedback for human-computer interaction |	GPIO 7
    name: Vibration Motor
    id: ${device_name}_motor
    entity_category: diagnostic
    icon: mdi:vibrate
    internal: false

script:
  # vibrate/haptics
  - id: vibrate
    then: 
      - switch.turn_on: ${device_name}_motor
      - delay: 0.1s
      - logger.log: "vibrate"
      - switch.turn_off: ${device_name}_motor

  - id: vibrate_on
    then: 
      - switch.turn_on: ${device_name}_motor
      - delay: 0.1s
      - logger.log: "vibrate ON"

  - id: vibrate_off
    then: 
      - switch.turn_off: ${device_name}_motor
      - delay: 0.1s
      - logger.log: "vibrate OFF"

## Lounge Dimmer Scripts ##
###########################
  - id: toggle_lounge_light
    then:
      - homeassistant.service:
          service: light.toggle
          data:
            entity_id: ${light_entity_lounge}

  - id: light_toggle_vibrate
    then: 
      - switch.turn_on: ${device_name}_motor
      - delay: 0.1s
      - logger.log: "light_toggle_vibrate"
      - switch.turn_off: ${device_name}_motor
      - homeassistant.service:
          service: light.toggle
          data:
            entity_id: ${light_entity_lounge}

  - id: long_vibrate
    then:
      - switch.turn_on: ${device_name}_motor
      - delay: 2s
      - logger.log: "long vibrate"
      - switch.turn_off: ${device_name}_motor

  - id: display_off
    then:
      - light.turn_off: ${device_name}_backlight
  - id: display_on
    then:
      - light.turn_on: ${device_name}_backlight


binary_sensor:
  - platform: template
    id: is_motor_running
    on_press:
      then:
        - switch.turn_on: ${device_name}_motor             # Turn on motor.
        
    on_release:
      then:
        - switch.turn_off: ${device_name}_motor            # Turn off motor.
##Hall encoder	
## Hall encoder is used for rotating operation in human-computer interaction, and orthogonal encoder is adopted
## GPIO 5、6
  # - platform: gpio
  #   pin: 
  #     number: 6 #17 
  #   name: Turn Left # is okay
  #   internal: false
  #   id: ${device_name}_gpio6_debounced
  #   on_press:
  #     then:
  #       - script.execute: lounge_light_decrease
  #       - logger.log:
  #           format: "rotate left. Calling script light decrease."
  #           level: DEBUG
  #       # - script.execute: vibrate   # Run the motor.
  # - platform: gpio
  #   pin: 
  #     number: 5 #16
  #   name: Turn Right
  #   id: ${device_name}_gpio5_debounced
  #   internal: false
  #   on_press:
  #     then:
  #       - script.execute: lounge_light_increase
  #       - logger.log:
  #           format: "rotate right. Calling script light increase."
  #           level: DEBUG
  #   #     - script.execute: vibrate   # Run the motor.


  - platform: gpio
    pin: 
      number: 3
#      mode: INPUT_PULLUP
#      inverted: true
      mode:
        input: true
        pullup: true
    name: Button
    internal: false
    id: ${device_name}_button
    icon: mdi:circle-outline
## Cant get it to work reliably    
    filters:
#      - invert:
      - delayed_on: 200ms 
      # When a signal ON is received, wait until publishing an ON state. If an OFF value is received while waiting, the ON action is discarded. 
      # Only send an ON value if the binary sensor has stayed ON for at least the specified time period. 
      ## Useful for debouncing push buttons.
      - delayed_off: 100ms 
      # When a signal OFF is received, wait until publishing an OFF state. 
      # If an ON value is received while waiting, the OFF action is discarded. 
      # Only send an OFF value if the binary sensor has stayed OFF for at least the specified time period. 
      ## Useful for debouncing push buttons.
      - delayed_on_off: 300ms 
      # Only send an ON or OFF value if the binary sensor has stayed in the same state for at least the specified time period. 
      ## Useful for debouncing binary switches.
    on_press:
      then:
        - script.execute: vibrate
        - script.execute: toggle_lounge_light
psram:
  mode: octal
  speed: 80MHz

spi:
  - id: lcd_spi
    clk_pin:
      number: 47
      allow_other_uses: true
    mosi_pin:
      number: 41
      allow_other_uses: true
display:
  - platform: st7701s
    id: ${device_name}_display

    # XXX DEBUG
    show_test_card: true
    lambda: |-
      it.fill(Color::WHITE);
    auto_clear_enabled: true
    update_interval: never #5s
    spi_mode: MODE3 #MODE0
    data_rate: 2MHz #10MHz
    color_order: BGR
    dimensions:
      width: 480
      height: 480
    invert_colors: true
    transform:
      mirror_x: true
      mirror_y: true
    cs_pin: 21
    de_pin: 39
    hsync_pin: 40
    vsync_pin: 48
    pclk_pin:
      number: 45
      ignore_strapping_warning: true
    init_sequence:
      - 1
      # https://github.com/wireless-tag-com/ZX2D10GE01R-V4848/blob/ad21b3659527618fdd752cc0801b0a36f6c5e52c/main/screen.c
      - [0xFF, 0x77, 0x01, 0x00, 0x00, 0x13]
      - [0xEF, 0x08]
      - [0xFF, 0x77, 0x01, 0x00, 0x00, 0x10]
      - [0xC0, 0x3B, 0x00]        # Scan line
      - [0xC1, 0x0B, 0x02]        # VBP
      - [0xC2, 0x07, 0x02]
      - [0xCC, 0x10]
      - [0xCD, 0x08]              # RGB format // ?565??? 666??
      - [0xB0, 0x00, 0x11, 0x16, 0x0e, 0x11, 0x06, 0x05, 0x09, 0x08, 0x21, 0x06, 0x13, 0x10, 0x29, 0x31, 0x18]   # IPS // 255 // 251 // 247 down // 239 // 231 // 203 // 175 // 147 // 108 // 80 // 52 // 24 // 16 // 8 down // 4 // 0
      - [0xB1, 0x00, 0x11, 0x16, 0x0e, 0x11, 0x07, 0x05, 0x09, 0x09, 0x21, 0x05, 0x13, 0x11, 0x2a, 0x31, 0x18]   # IPS // 255 // 251 // 247 down // 239 // 231 // 203 // 175 // 147 // 108 // 80 // 52 // 24 // 16 // 8 down // 4 // 0
      - [0xFF, 0x77, 0x01, 0x00, 0x00, 0x11]
      - [0xB0, 0x6d]              # VOP  3.5375+ *x 0.0125 // 5D
      - [0xB1, 0x37]              # VCOM amplitude setting
      - [0xB2, 0x81]              # VGH Voltage setting // 12V
      # - [0xB3, 0x80]
      - [0xB5, 0x43]              # VGL Voltage setting // -8.3V
      - [0xB7, 0x85]
      - [0xB8, 0x20]
      - [0xC1, 0x78]
      - [0xC2, 0x78]
      - [0xD0, 0x88]
      - [0xE0, 0x00, 0x00, 0x02]
      - [0xE1, 0x03, 0xA0, 0x00, 0x00, 0x04, 0xA0, 0x00, 0x00, 0x00, 0x20, 0x20]
      - [0xE2, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      - [0xE3, 0x00, 0x00, 0x11, 0x00]
      - [0xE4, 0x22, 0x00]
      - [0xE5, 0x05, 0xEC, 0xA0, 0xA0, 0x07, 0xEE, 0xA0, 0xA0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      - [0xE6, 0x00, 0x00, 0x11, 0x00]
      - [0xE7, 0x22, 0x00]
      - [0xE8, 0x06, 0xED, 0xA0, 0xA0, 0x08, 0xEF, 0xA0, 0xA0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      - [0xEB, 0x00, 0x00, 0x40, 0x40, 0x00, 0x00, 0x00]
      - [0xED, 0xFF, 0xFF, 0xFF, 0xBA, 0x0A, 0xBF, 0x45, 0xFF, 0xFF, 0x54, 0xFB, 0xA0, 0xAB, 0xFF, 0xFF, 0xFF]
      - [0xEF, 0x10, 0x0D, 0x04, 0x08, 0x3F, 0x1F]
      - [0xFF, 0x77, 0x01, 0x00, 0x00, 0x13]
      - [0xEF, 0x08]
      - [0xFF, 0x77, 0x01, 0x00, 0x00, 0x00]
      - [0x3A, 0x66]              # 55/50=16bit(RGB565);66=18bit(RGB666);77?????3AH?=24bit(RGB888)

    hsync_pulse_width: 10
    hsync_back_porch:  10
    hsync_front_porch: 10
    vsync_pulse_width:  2
    vsync_back_porch:  12
    vsync_front_porch: 14
    pclk_frequency: 12MHz #15MHz
    pclk_inverted: false
    data_pins:
      red:
        - number: 10        #R1
        - number: 16        #R2
        - number: 9         #R3
        - number: 15        #R4
        - number: 46        #R5
          ignore_strapping_warning: true
      green:
        - number: 8         #G0
        - number: 13        #G1
        - number: 18        #G2
        - number: 12        #G3
        - number: 11        #G4
        - number: 17        #G5
      blue:
        - number: 47        #B1
          allow_other_uses: true
        - number: 41        #B2
          allow_other_uses: true
        - number: 0         #B3
          ignore_strapping_warning: true
        - number: 42        #B4
        - number: 14        #B5
